### ISSUE TITLE
Tracking: `tq` package

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#1764]
This issue serves as a place to track the remaining 👊-items for merging `tq-master` into `master`.

**Original proposal**: #1651.

## To-do

- [x] #1758: Priority Retries
- [x] #1767: De-couple `config` package, use interface instead.
- [x] #1774 Change `Begin` function to use a `*tq.Manifest`
- [x] #1772: Introduce a `tq.Object` to replace use of `*tq.Transfer`, `tq.Transferable` and `*api.ObjectResource`.
- [ ] Split adapter implementations into sub-package: `tq/transferadapter` (name pending).

---

/cc @git-lfs/core

**Comment by technoweenie** [comment]
I ran into an issue with `Begin()`, the custom adapter can use a different setting if the implementation is not concurrent: https://github.com/git-lfs/git-lfs/blob/39badd3c74bca15afd1e1e4774094f17895088d7/tq/custom.go#L109-L121

One thought is to make it a single struct, and change the [caller](https://github.com/git-lfs/git-lfs/blob/39badd3c74bca15afd1e1e4774094f17895088d7/tq/transfer_queue.go#L532-L539) to pass in a new struct:

```diff
 func (q *TransferQueue) ensureAdapterBegun() error {
	q.adapterInitMutex.Lock()
	defer q.adapterInitMutex.Unlock()

	if q.adapterInProgress {
		return nil
	}

-	// Progress callback - receives byte updates
-	cb := func(name string, total, read int64, current int) error {
-		q.meter.TransferBytes(q.transferKind(), name, read, total, current)
-		return nil
-	}

	tracerx.Printf("tq: starting transfer adapter %q", q.adapter.Name())
-	err := q.adapter.Begin(config.Config.ConcurrentTransfers(), cb)
+	err := q.adapter.Begin(BeginArgs{
+		ConcurrentTransfers: config.Config.ConcurrentTransfers(),
+		ProgressCallback: func(name string, total, read int64, current int) error {
+			q.meter.TransferBytes(q.transferKind(), name, read, total, current)
+			return nil
+		},
+	})
```

This gives us the flexibility to add more to `BeginArgs` in the future. It also gives adapters the flexibility to set their own values without worrying about affecting other adapters. Finally, we could add `ConcurrentTransfers` to `*tq.Manifest` and get rid of `config.Config.ConcurrentTransfers()`.

**Comment by technoweenie** [comment]
Okay, I think I have a good compromise. #1767 now adds a `(*tq.Manifest) ConcurrentTransfers()` func. So, we can just update the interface to:

```go
type BeginArgs interface {
  ConcurrentTransfers() int
}

// ...

err := q.adapter.Begin(q.manifest, cb)
```

This lets us add more properties to `*tq.Manifest`, while providing a tighter interface that doesn't have any of the `*tq.Manifest` functions that get adapters (totally unnecessary inside of an adapter). We may not ever need more than `ConcurrentTransfers()`, but this way it's pretty easy to add more properties.

**Comment by ttaylorr** [comment]
Awesome compromise. This looks great! ✨

**Comment by technoweenie** [comment]
I'm making a note of some things while reviewing #1772 I noticed that should be un-exported before `tq` lands in master:

* `tq.NewTransfer()`
* `tq.Batch`

I think these can go too IMO.

* `lfs.NewDownloadable()`
* `lfs.NewUploadable()`

**Comment by ttaylorr** [comment]
> I think these can go too IMO.
> 
> * `lfs.NewDownloadable()`
> * `lfs.NewUploadable()`

Removed in #1776 😄

**Comment by ttaylorr** [comment]
> I noticed that should be un-exported before `tq` lands in master:
> 
> * `tq.NewTransfer()`
> * `tq.Batch`

Un-exported in #1777.

**Comment by ttaylorr** [comment]
> * [ ] Split adapter implementations into sub-package: `tq/transferadapter` (name pending).

Re-prioritized this to occur after merging `tq-master` into `master`.

**Comment by ttaylorr** [comment]
Merged `tq-master` into `master`. Thanks everybody 😄
