### ISSUE TITLE
Proposal: `lfsapi` package for v2.0.0

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#1783]
# `lfsapi` Proposal

Today, in order to interact with an API inside git-lfs, you have to import the
`api` package, which depends on `httputil`, `auth`, and of course, a
`*config.Configuration`. That adds up to a pretty heavy dependency.

Packages should be able to interact with the LFS API without importing such
a large set of dependencies. To do this, we can evolve the same philosophy that
applied to the `config` package: by reducing the scope of domain knowledge that
the package (`api`) owns, we can distribute calling code that uses it further
as the dependency will loose weight.

This much more closely matches the philosophy of the `net/http` package.
Clients would be able to make their own `*http.Request` instances, passing
them into the `*api.Client.Do` function.

This package should allow easy access to the following domains, while still keeping things lightweight:

* Endpoint resolving (experimented with in https://github.com/git-lfs/git-lfs/pull/1770)
* Git Credentials
* Netrc
* NTLM
* SSH auth
* HTTP request logging and redirection handling

By reducing the set of primitives exposed by an API package, we can remove the
tight coupling that currently exists in the `locking` package between service
classes and API calls.

Right now, that looks something like:

```go
s, resp := c.apiClient.Locks.Lock(&api.LockRequest{
	Path:               path,
	Committer:          api.NewCommitter(c.cfg.CurrentCommitter()),
	LatestRemoteCommit: latest.Sha,
})

if _, err := c.apiClient.Do(s); err != nil {
	return Lock{}, fmt.Errorf("Error communicating with LFS API: %v", err)
}

if len(resp.Err) > 0 {
	return Lock{}, fmt.Errorf("Server unable to create lock: %v", resp.Err)
}

lock := c.newLockFromApi(*resp.Lock)
```

But it could be reduced down to:

```go
lockReq := &api.LockRequest{
  Path:               path,
  Committer:          api.NewCommitter(c.cfg.CurrentCommitter()),
  LatestRemoteCommit: latest.Sha,
}

endpoint := apiClient.Endpoint("master", "download")
req, _ := http.NewRequest("POST", "/locks", jsonToIOReader(lockReq))
res, _ := apiClient.Do(endpoint, req)
defer res.Body()

var lockRes LockResponse
unmarshalBody(res.Body, &lockRes)
```

This enables packages like `tq` to define their own API interfaces,
perhaps like:

```go
package tq

type Batcher struct {
	c *lfsapi.Client
}

func (b *Batcher) Batch(direction string, oids []string) (*BatchResponse, error) {
	// ...
}
```

As a critical note: `lfsapi` would _no longer_ be the single source of all LFS
APIs. Instead, it will be a package that is depended on by other packages which
themselves implement the API. This corrects our package structure to be much more
in-line with Go's packaging philosphy.

In addition, the code is much closer to how Go HTTP requests look. However, how
do we deal with non-http protocols? We can use Go's ability to
register custom protocols in `net/http`:

```go
t := &http.Transport{}
t.RegisterProtocol("ssh", sshRoundTripper())
c := &http.Client{Transport: t}
```

Implementing a custom http roundtripper is easy. Implementing SSH
could be as simple as converting a request that looks like:

    ssh://git@gitserver.com/git-lfs-authenticate?args=foo/bar%20download

To an SSH command like:

    ssh git@gitserver.com git-lfs-authenticate foo/bar download

A Go roundtripper function would then convert the SSH command results
into an `*http.Response` that the client code expects.

We could also use this to support `file://` natively, letting LFS
work across local repositories.

* [x] Batch API #1827
* [x] BatchSingle API
* [x] Verify API
* [x] Locking API #1824
* [x] TUS Adapter #1827
* [x] Basic Download Adapter #1827
* [x] Basic Upload Adapter #1827
* [x] Per-Host SSL Certs #1787
* [x] HTTP Proxy #1787
* [x] HTTP timeouts #1787
* [x] NTLM Support #1838
* [x] Netrc Support #1784
* [x] Git Credential Support #1784
* [x] SSH Credential Support #1837
* [x] HTTP Redirections #1791
* [x] UserAgent #1791
* [x] HTTP Verbose Logging and Stats #1794

---

/cc @git-lfs/core

**Comment by technoweenie** [comment]
I like the idea of there being two distinct steps: Build a request, and then get a response back for that request. We can probably rearrange the above to something like:

```go
// get the endpoint for 'master' remote, then use that to build a full uri with '/locks'
req, _ := apiClient.NewRequest("master", "POST", "/locks", jsonToIOReader(lockReq))

// maybe you have the endpoint instance for some reason...
req, _ := endpoint.NewRequest("POST", "/locks", jsonToIOReader(lockReq))

// make the request, follow redirects
res, _ := apiClient.Do(req)
```

Auth isn't in the example either. It's currently implicit, but it's not completely up to a `*http.Request` 
whether it needs auth or not. That idea lead to weird stuff [like this](https://github.com/git-lfs/git-lfs/blob/85c570942babfeb84925f5e26fe6deeaeda620d5/auth/credentials.go#L129-L130).

Sometimes, that decision is made outside of the `*http.Request`, like [here](https://github.com/git-lfs/git-lfs/blob/85c570942babfeb84925f5e26fe6deeaeda620d5/tq/basic_download.go#L113). We could either go with:

```go
// extra auth bool
res, _ := apiClient.Do(req, !foo.Authenticated)

// option func, lol
res, _ := apiClient.Do(req)
res, _ := apiClient.Do(req, api2.Auth(foo.Authenticated))

// separate methods
if foo.Authenticated {
  res, _ := apiClient.Do(req)
} else {
  res, _ := apiClient.DoWithAuth(req)
}

// handle this outside of Do()
req, _ := apiClient.NewRequest("master", "POST", "/locks", jsonToIOReader(lockReq))
if !foo.Authenticated {
  apiClient.Authenticate(req)
}
res, _ := apiClient.Do(req)
```

Not really in love with any of them, but would probably lean towards the first one (the bool arg) or the 3rd one (separate methods).

**Comment by ttaylorr** [comment]
I think it's really good that these are explicit to the caller. We should reduce the magic as much as possible so callers know what/where they're getting things back from.

I think some of these positional arguments would be good candidates for the `OptionFn` pattern. I think from the original list in the issue, the following could be options:

- Endpoint resolving (experimented with in #1770)
- NTLM
- SSH auth

```go
var body io.Reader
c.Do("POST", body, api.WithEndpoint("origin", "locks"))
```

**Comment by technoweenie** [comment]
That example doesn't feel right at all to me. All requests need at least a url, so I'm not sure why it'd be an optional func arg of `Do()`.

Also, NTLM and SSH Auth stuff are determined by the endpoint:

* NTLM is used if `lfs.$uri.access=ntlm`
* SSH Auth is used if the git remote url is an SSH address.

**Comment by ttaylorr** [comment]
> That example doesn't feel right at all to me.

Thinking a little bit more about this, I agree. I think what I wanted to happen was for the `*api.Client` to relativize the path against an optional endpoint, but I feel not great about that for two reasons:

1. The endpoint is required
2. The internal relativization is magical

I think the later of those is directly opposing our goals here, and I think your suggestion of multiple functions is much better 👍.

**Comment by sinbad** [comment]
I like the explicitness of `DoWithAuth` too, particularly as it probably resolves to a pre-step to the regular `Do`. 

If we're planning on supporting non-HTTP with this work though, we need to consider that for some protocols the auth is handled by the protocol, e.g. SSH keys. But maybe if we just use the existing approach of only flagging the endpoint as needing auth when it fails with an auth error, that is covered. 

I'm a little uneasy with using HTTP as a wrapper for non-HTTP protocols for reasons I can't quite put my finger on right now. I guess the main issue is that wrapping it this way may make it harder to represent stateful protocols, of which SSH is one - although not the way we use it right now, which is simply a one time authentication call & response. For any more significant exchange, it's very expensive to keep launching a new ssh client for every request; usually you'd establish the connection once and re-use it on a timeout. Maybe your round tripper can do that internally, I'm not sure since I haven't written one before. Something to consider anyway, could be it works fine.

**Comment by technoweenie** [comment]
> I'm a little uneasy with using HTTP as a wrapper for non-HTTP protocols for reasons I can't quite put my finger on right now.

I think I have a similar sense of unease. However, http round trippers have to be initialized once, so it is definitely possible to have add a global teardown phase for the lfsapi client. There isn't one currently, since HTTP is all we use. I've had good luck with using roundtrippers for non-HTTP stuff, but I've never had to maintain stateful connections.

I think this effort is a major improvement over the existing code. If we find that the API has to change to support alternate protocols, we'll cross that bridge when we get to it.

**Comment by technoweenie** [comment]
With #1824 and #1827, we have everything moved over, except NTLM. All tests pass :) (meaning, we don't have any NTLM or SSH auth tests yet).

**Comment by technoweenie** [comment]
Hey @WillHipschman, are there any NTLM-powered LFS services that I can use for testing? Is it even possible outside of a windows domain?

**Comment by WillHipschman** [comment]
I don't think anybody uses ntlm outside of windows.

You'l need a ntlm server to be able to test it. There might be some stub ones on github somewhere, or you can use an on-premise instance of VSTS (https://www.visualstudio.com/team-services/), but i don't know how easy it is to set up free on-premise vsts server.

I'm not at Microsoft anymore, but @kevin-david might be able to direct you to someone who can get you set up with one.

**Comment by kevin-david** [comment]
@technoweenie, if you are willing to install it, you can download the trial of TFS 2017 which has LFS support inside git repos. Here's the trial download: https://www.visualstudio.com/tfs/. 

We also have a non-trial free version (TFS Express) but I can't find a download link outside MSDN - let me know if you need that version instead and I'll see if I can find somewhere to host it.

I'm not familiar enough with NTLM to tell you if it'll work outside a domain, sorry :(

/cc @derrickstolee since he's responsible for LFS on our team now.

**Comment by derrickstolee** [comment]
To add to @kevin-david, I want to point out that currently Git for Windows has a bug regarding NTLM and you'll need to downgrade to 2.10.1 until they fix it. The bug causes all NTLM-based git pushes to fail, not just LFS.

**Comment by technoweenie** [comment]
@kevin-david, @derrickstolee: thanks for the info re: NTLM. I managed to [implement the protocol in our tests](https://github.com/git-lfs/git-lfs/blob/ac9ad7d8175a181fdd2a6ffab2bf07f9c3938080/lfsapi/ntlm_test.go#L18), so I'm now reasonably sure that it all works. I'm working on an integration test too in #1836. This at least gives me some confidence that it all works.

I'll see if I can get TFS working on my home PC to try it for real though.
