### ISSUE TITLE
Tracking: Locking backports

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#1819]
This issue serves to track back-porting the series of internal changes made to locking-related commands.

- [x] git-lfs/git-lfs#1814: add `--json` support
- [x] git-lfs/git-lfs#1815: teach pre-push to check locks
- [x] git-lfs/git-lfs#1816: add pre-commit hook
- [x] git-lfs/git-lfs#1817: add post-merge hook
- [x] git-lfs/git-lfs#1818: make API calls against `repo.git/info/lfs/locks` instead of `/locks`

---

/cc @git-lfs/core
