### ISSUE TITLE
investigate pre-push hook.

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#56]
Git 1.8.2 has a pre_push hook.  We should use that to run `git media push`.  Let's use that so we don't have to worry about wrapping `git push`.
- [x] Add pre-push hook #62
- [x] `git media init` adds hook if run inside a repository. #62
- [ ] The git media clean/smudge filters also install hooks when run inside a repository. #65

The goal is for this to work:

```
# the smudge filter downloads media files, and installs the hook locally.
$ git clone https://github.com/github/big-repo

# the clean filter queues the file to be uploaded, and installs the hook locally.
# this is useful in case the `clone` didn't have any big media files.
$ git add some-big-file.mov

$ git commit -m "whatevs"
$ git push # runs pre-push
```
